### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by ajk68** [briansunter/logseq-plugin-gpt3-openai#1]
Thanks for the GPT3 plugin! Unfortunately, i'm consistently getting OpenAi Plugin Error with each /gpt3 request.

<img width="405" alt="Screenshot 2022-06-06 at 10 17 52" src="https://user-images.githubusercontent.com/60648426/172123872-987340a7-f283-498a-a5ef-206c788ab3d9.png">
 
I created a new api key specifically for this plugin and OpenAI shows it has been used, so looks like an authenticated request was sent by the plugin and received by openai.

The console doesn't show much else apart from a 400 error.
<img width="537" alt="Screenshot 2022-06-06 at 10 17 33" src="https://user-images.githubusercontent.com/60648426/172122925-e2938ca5-3efd-4d7f-a82b-aa20b063a57b.png">

Could you please help me find a solution?

**Comment by ajk68** [comment]
Just managed to get it working by running the local dev server. The moment i stop the vite server, i get the plugin error back. I assumed the packaged plugin would run standalone, and vite server was only needed for plugin developers.

**Comment by briansunter** [comment]
@ajk68 if possible would you mind checking the "network" tab while running the command and seeing what the error response from the /completions endpoint is?

**Comment by ajk68** [comment]
After reinstalling the plugin, it now works completely fine! Don't know what was causing the problem, but obviously it works brilliantly now...  Wish i had this while i was still in university :-)

<img width="837" alt="Screenshot 2022-06-07 at 14 57 54" src="https://user-images.githubusercontent.com/60648426/172385746-96b7b566-e1d1-4756-b29b-1e6f6f38e82f.png">

Thanks for your work on this plugin! 

BTW: Are you planning to add a slashCommand or contextMenuItem for tl;dr? Thought i saw this in one of the screenshots. Might be interesting to come up with a few prompts that generally work well for summarizing, or asking questions about the text or coming up with related concepts. Would be interested in learning best practises for using GPT3 to assist thinking.

**Comment by briansunter** [comment]
Awesome @ajk68 glad it's working. Feel free to open another issue if you notice anything off.

I really appreciate the feedback and suggestions. I added some items to the product roadmap.

#8 is the top feature I'm working on 
#12 
#9 

Closing this for now since it seems to be working for you, but feel free to open another issue if you encounter a bug or have an idea.
