### ISSUE TITLE
Add proxy server configuration option for improved network speeds

### ISSUE THREAD

**Issue by p1s1lver** [briansunter/logseq-plugin-gpt3-openai#101]
Dear developer,

I hope this message finds you well. I am a user of your logseq-plugin-gpt3 project and I have been experiencing slow network speeds when using the project from China. I believe this is due to the lack of a proxy server configuration option in the project.

I would like to kindly request that you consider adding a proxy server configuration option to the project, so that users from China can enjoy faster network speeds. I understand that this may require some additional work on your part, but I believe it would greatly benefit the project and its users.

Thank you for your time and consideration. Please let me know if there is anything I can do to assist with this request.

Best regards, p1s1ver.

Let me know if you have any other questions or if there's anything else I can help you with!

**Comment by guiling-2000** [comment]
Yes, I really need this feature as well.

**Comment by scbizu** [comment]
@p1s1lver Logseq already has the builtin Proxy configuration in: `Menu -> Advance -> Network Proxy` . You can set it and check if it works as expected .

<img width="933" alt="CleanShot 2023-04-30 at 22 55 22@2x" src="https://user-images.githubusercontent.com/8732481/235359906-034b5872-589e-4ac5-8bd9-9da53b8f8c7d.png">

**Comment by p1s1lver** [comment]
> @p1s1lver Logseq already has the builtin Proxy configuration in: `Menu -> Advance -> Network Proxy` . You can set it and check if it works as expected .
> 
> <img alt="CleanShot 2023-04-30 at 22 55 22@2x" width="933" src="https://user-images.githubusercontent.com/8732481/235359906-034b5872-589e-4ac5-8bd9-9da53b8f8c7d.png">

thanks bro

**Comment by briansunter** [comment]
Looks like this should be implemented in #110 
Feel free to reopen if anything else is needed!
