### ISSUE TITLE
Which Whisper model is used?

### ISSUE THREAD

**Issue by nhan000** [briansunter/logseq-plugin-gpt3-openai#102]
Hi I have a question. 

Which Whisper model is used to transcribe the audio? It's really fast but the result is terrible for regular audio recordings (lecture recordings for example).

Could you add an option for people to choose between different models? Thanks a lot!

**Comment by nhan000** [comment]
Per OpenAI documentation you can use the large model [Models - OpenAI API](https://platform.openai.com/docs/models/whisper)
![image](https://user-images.githubusercontent.com/85216095/226691699-126a8e79-ce31-46e1-86d4-e32f24b2bc3a.png)

**Comment by briansunter** [comment]
Hey @nhan000 it should be the whisper v2 large which they call “whisper-1” in their AI. This should be the largest/best model and it’s the only one they have available via their api. I'd be curious on the differences between output between locally and in logseq when running it on the same files.
