### ISSUE TITLE
multiple blocks selection not functioning

### ISSUE THREAD

**Issue by jenningsb2** [briansunter/logseq-plugin-gpt3-openai#103]
When I select multiple blocks and open the GPT dialog, it returns nonsense. It seems to be working on the single block or page level. 

I suspect nothing is sent to the prompt when selecting multiple blocks.

Here is a video of the issue:

https://user-images.githubusercontent.com/29644050/227810710-c92ff41d-dd32-4582-9478-598202861de2.mp4

**Comment by jenningsb2** [comment]
Nevermind 😂 

I was on an old version! My bad man.

**Comment by briansunter** [comment]
No worries, hope you enjoy the plugin!
