### ISSUE TITLE
can't install plugin from the app store?

### ISSUE THREAD

**Issue by jtan7th** [briansunter/logseq-plugin-gpt3-openai#108]
![image](https://user-images.githubusercontent.com/96033630/231040054-43cc1252-d148-4e8b-b4fe-7ecc4d5460fd.png)

Hi - love the idea of using GPT-3 on logseq but got this image when I tried to install it, is there something that I'm doing wrong or needed to do beforehand?

**Comment by juanjonavarro** [comment]
It seems like it's trying to connect to your localhost (127.0.0.1 on port 7769). Perhaps you have a non-working proxy configured?

**Comment by briansunter** [comment]
Seems like a logseq/github rate limiting issue. Try it again and see if it works

**Comment by briansunter** [comment]
Closing this since it seems like a github rate limiting issue. Try asking in the logseq discord if you keep seeing this
