### ISSUE TITLE
FR: add option to set URL for localAI server instead of openAI

### ISSUE THREAD

**Issue by andreklug** [briansunter/logseq-plugin-gpt3-openai#113]
With the availability of localAI (which offers an openAI compatible REST API) it would be great if this plugin offered the possibility to set an individual URL for the API to call. 

https://github.com/go-skynet/LocalAI

Using localAI would mitigate concerns about working with any kind of sensitive or business related information for me and hopefully others as well.

**Comment by briansunter** [comment]
Just merged this in #110 let me know if this works for you!
