### ISSUE TITLE
403 (forbidden)

### ISSUE THREAD

**Issue by megamanenm** [briansunter/logseq-plugin-gpt3-openai#143]
Every time I try to use any gpt command, it says "error" "unknown error" with a 403 forbidden in the console. It used to work before. Does anyone know what's happening?

**Comment by briansunter** [comment]
Hello, I pushed some updates that might fix this. Could you try updating and restarting logseq?

**Comment by megamanenm** [comment]
I restarted logseq and tried again, /gpt still returns this "unknown error". I tried both the user and project type of openAI API key, but no difference. I'm on logseq version 0.10.9 if that matters?

**Comment by briansunter** [comment]
Could you attach a screenshot of the error in the console? That should give more info on the error

https://github.com/briansunter/logseq-plugin-gpt3-openai?tab=readme-ov-file#debugging

**Comment by megamanenm** [comment]
> Could you attach a screenshot of the error in the console? That should give more info on the error
> 
> https://github.com/briansunter/logseq-plugin-gpt3-openai?tab=readme-ov-file#debugging

![Screenshot from 2024-10-23 10-40-59](https://github.com/user-attachments/assets/83b67020-6d23-4747-9c65-30624ac0e656)

Like this?

**Comment by megamanenm** [comment]
Okay what is this UI lmao, I had no feedback that anything was actually happening when pressing that button, ignore that 🗿

**Comment by briansunter** [comment]
It looks like it's using an old url. This should have been fixed in the latest update, but if you go into settings and make sure `https` is at the beginning and not `http` that might fix it.

**Comment by megamanenm** [comment]
> It looks like it's using an old url. This should have been fixed in the latest update, but if you go into settings and make sure `https` is at the beginning and not `http` that might fix it.

No way, that fixed it! Thanks a lot!
