### ISSUE TITLE
TL;DR not appearing at the slash command

### ISSUE THREAD

**Issue by harshadwaj** [briansunter/logseq-plugin-gpt3-openai#17]
/tldr is not appearing at the end of the block as shown in the summarization example.
Installed through marketplace. v1.0.3

**Comment by asifm** [comment]
Can confirm it's not there.

Windows 10
Logseq 0.7.3
Extension 1.0.1

**Comment by briansunter** [comment]
Sorry, this made it into the video but not MVP, so manually add that tl;dr prompt until I finish the prompt templates like this one.

**Comment by briansunter** [comment]
Added this in #70
