### ISSUE TITLE
Block Context MenuItem for specific prompt?

### ISSUE THREAD

**Issue by ajk68** [briansunter/logseq-plugin-gpt3-openai#23]
Hi Brian,

Big fan of your gpt3 plugin! Use it a lot. Tnx!

I noticed in your bubble sort algorithms video that you had a BlockContextMenuItem "Explain Code". I'm assuming it adds a specific prompt with the block content. 

Would be great if the plugin would allow for a few custom menuItems with specific prompts for things like summarizing, rewriting, explaining a concept, completing a text, pro/cons, etc. 

Is that anything you consider adding? 

Arthur

**Comment by briansunter** [comment]
I'm hoping to get this out soon with #9 and #18. Want to include some defaults like the code one as well as let users define their own. I'm testing it now.

**Comment by ajk68** [comment]
tnx, cool stuff!

**Comment by briansunter** [comment]
Added this in #70 in the popup. If you'd like to see this in the block context menu as well please feel free to re-open!
