### ISSUE TITLE
Does the plugin take into account previous text blocks?

### ISSUE THREAD

**Issue by preslavrachev** [briansunter/logseq-plugin-gpt3-openai#26]
I love how the GPT-3 plugin works as it is, and I would gladly use it even further. For instance, for Q&A style investigations into a certain topic. Those require that I send the entire conversion to the API, as it builds up. From my understanding, currently only the immediate text block is being processed. Is this the case, and do you have plans to extend it to take into account parent and sibling nodes as well?

P.S. I have not checked the code, so please, forgive me if it is already working. I could not find a suitable example in your list, which is why I am raising the issue.

**Comment by briansunter** [comment]
Hey @preslavrachev 
This is one of the top features I'm working on, sending child blocks to gpt3 to save context

https://github.com/briansunter/logseq-plugin-gpt3-openai/issues/8

**Comment by briansunter** [comment]
It should take into account full pages with `gpt-page` now. Feel free to re open if you have other ideas on how this should work! I'm working on additional options like "multi select" and sending a tree of nested blocks as well.
