### ISSUE TITLE
DALL-E API integration

### ISSUE THREAD

**Issue by briansunter** [briansunter/logseq-plugin-gpt3-openai#43]
https://venturebeat.com/ai/openai-shares-dall-e-api-use-case-in-advance-of-autumn-release/

**Comment by AvijeetPrasad** [comment]
Hi, thanks for the awesome plugin. I am wondering if we can use DALL-E 2 API in future. I guess we are currently using DALL-E.

**Comment by briansunter** [comment]
Yup! We are actually already are using the dall-e 2 API!
