### ISSUE TITLE
Plugin Settings do not open to insert API Key 

### ISSUE THREAD

**Issue by CSilvaGit** [briansunter/logseq-plugin-gpt3-openai#54]
I'm trying to install the GPT3-OpenAI plugin in my LogSeq graph and I can't seem to open the plugin settings, nothing happens when I click the gear button. 

Can this be an issue with the plugin or can it be from LogSeq?

Thanks.

**Comment by CSilvaGit** [comment]
Hi Brian, thanks for the feedback. Yesterday I checked for logseq updates and after installing version 0.8.11 it was fixed.

**Comment by briansunter** [comment]
Awesome 👍
