### ISSUE TITLE
"Unkown OpenAI error" when chosing gpt-block oder gpt-page

### ISSUE THREAD

**Issue by fhold** [briansunter/logseq-plugin-gpt3-openai#55]
I installed the plugin and also inserted an API Key, but when i try to use gpt3 i get "Unknown OpenAI Error". 
Im running version 08.11 windows of logseq. 
Interestingly the dalle command works fine

**Comment by briansunter** [comment]
Would you mind checking the error console for messages? I have a debugging guide here https://github.com/briansunter/logseq-plugin-gpt3-openai#debugging

**Comment by briansunter** [comment]
Let me know if this is still an issue. There's better error messaging in the latest version. Other users have tried making a new API key.

**Comment by h-b** [comment]
I'm also experiencing the same problem. I'm currently using Logseq 0.9.9 under Fedora and the GPT-3 OpenAI plugin v1.13.1. Even after generating a new API key, I'm still getting the 'Unknown OpenAI Error'. I've tried to follow the debug instructions on the provided URL, but I'm having trouble finding the 'View -> Toggle Developer Tools' menu, even though I've enabled developer mode in Logseq's advanced settings. Could you please help me locate this menu? Sorry if the answer is obvious, I just can't seem to find it. Thanks!
