### ISSUE TITLE
OpenAI plugin Error  on logseq

### ISSUE THREAD

**Issue by baramsivaramireddy** [briansunter/logseq-plugin-gpt3-openai#57]
![image](https://user-images.githubusercontent.com/71169645/202984501-786640d1-1403-4946-9299-8f4bd02a43cf.png)

i just installed the plugin . placed the api key correctly .

my observation .

after i type my query . firstly one request to the openai api is sent  and got 404 error  , later openai plugin error occured . later 
another request was made automatically  . but playload seems weird 

![image](https://user-images.githubusercontent.com/71169645/202985302-a57d050f-b73a-4746-ad6f-14f8c9d10fc8.png)

**Comment by briansunter** [comment]
Could you post a screenshot of the response on the `completions` request?

**Comment by baramsivaramireddy** [comment]
I tried with different api key. It worked. I completely used my free credits in openai api
