### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by oluckyman** [briansunter/logseq-plugin-gpt3-openai#58]
Would be great to have any kind of feedback, that the command is accepted and being processed.
Even a temporary text placeholder with `⏳` would be better than nothing.

P.S. thanks for the plugin! 🙏

**Comment by briansunter** [comment]
This is a really good idea. I'm working on a modal popup with a progress spinner so hopefully that will be a bit more user friendly. I'll look into adding some sort of indicator for the raw block prompts as well, a couple others have asked for this too.

**Comment by briansunter** [comment]
I added a popup with a progress spinner in the latest update. I could add one to the block/page commands as well, but I'm thinking of phasing out gpt-block and gpt-page in favor of the popup.

 Let me know what you think. If you still prefer the block commands and want a progress bar there as well, please feel free to re-open this issue!

**Comment by oluckyman** [comment]
I was not aware of `/gpt` command until you said. Yeah, the popup seems more convenient! thank you 🙏
