### ISSUE TITLE
[Feature] Rephrase block

### ISSUE THREAD

**Issue by forrestchang** [briansunter/logseq-plugin-gpt3-openai#65]
Add rephrase function like Roam.

<img width="1078" alt="CleanShot 2023-01-07 at 02 20 41@2x" src="https://user-images.githubusercontent.com/7857126/211074314-ded4a40f-03da-40eb-be07-34861d17f24d.png">

I will work on this issue.

**Comment by forrestchang** [comment]
The result 👇

![CleanShot 2023-01-07 at 03 02 06](https://user-images.githubusercontent.com/7857126/211081932-25627bb9-ff49-4f70-924d-fab2d18be75d.gif)

**Comment by briansunter** [comment]
Hey! I'm really interested in this feature. I'm finishing up a better way to integrate these prompts this week and I'll follow up out with instructions on how to add it there.

**Comment by briansunter** [comment]
Hey @forrestchang I added a feature to add built-in prompts to a text file. Definitely contribute anything you find useful! https://github.com/briansunter/logseq-plugin-gpt3-openai/blob/master/src/prompts/prompts.toml

**Comment by forrestchang** [comment]
> Hey @forrestchang I added a feature to add built-in prompts to a text file. Definitely contribute anything you find useful! https://github.com/briansunter/logseq-plugin-gpt3-openai/blob/master/src/prompts/prompts.toml

That's very cool! I will try it.
