### ISSUE TITLE
OpenAi Quota Reached

### ISSUE THREAD

**Issue by phreshsprout** [briansunter/logseq-plugin-gpt3-openai#69]
I've solved this problem for myself but others might benefit from these steps.
1) Most likely your API key was one generated during the initial trial, you must delete this after creating a new one. This trial time expires even though when looking casually at the usage on open.ai it looks like you have an unused credit. 
2) Delete old key and create new one AFTER you've upgraded your account to a paid subscription. If you attempt to do this before, you just keep creating new API key's that are expired trial keys.
3) After upgrading to a paid subscription, then generate a new API key and delete the old one.
4) Put this key into the gpt3 plugin and you will be good to go.

**Comment by briansunter** [comment]
This is really good feedback. I'll add this to the readme. If anyone else notices this, let me know.
