### ISSUE TITLE
cannot install the plugin due to the [Error]<logseq-plugin-gpt3-openai>

### ISSUE THREAD

**Issue by shrijeetshivdekar** [briansunter/logseq-plugin-gpt3-openai#79]
[Error]<logseq-plugin-gpt3-openai> :EPERM: operation not permitted, rename 'C:\Users\SHRIJE~1\AppData\Local\Temp\logseq-plugin-plugin-gpt3-openai' -> 'C:\Users\Shrijeet Shivdekar\.logseq\plugins\logseq-plugin-gpt3-openai'

**Comment by briansunter** [comment]
Hey @shrijeetshivdekar this looks like a windows or logseq issue. Try installing it again or asking in the logseq forums or dicord.

**Comment by briansunter** [comment]
Seems like this is a github/logseq issue. If it doesn't work after another try ask on the logseq forums or discord
