### ISSUE TITLE
Plugin Seems to Ignore Input and Return Demo Data?

### ISSUE THREAD

**Issue by mike-lu** [briansunter/logseq-plugin-gpt3-openai#80]
The current version of the plugin seems to not take in any input. See screen recording below for some notes I took on an article about the current state of the tech industry. When I asked the plugin to summarize, I got three entirely different summaries each time I asked it to regenerate:

1. Technology and internet in the classroom
2. The benefits of owning a pet
3. The history of photographic film.

I know GPT can be occasionally bewildering, but this seems like it's getting input from something else entirely. 

![Untitled](https://user-images.githubusercontent.com/1834535/215894646-363b8c2f-fa47-482a-9a36-21b157c6c4ef.gif)

Thanks!

**Comment by briansunter** [comment]
Hey @mike-lu when using the built-in commands make sure your cursor is inside the block you want to use as input.

I just made an issue here to make this less error-prone, https://github.com/briansunter/logseq-plugin-gpt3-openai/issues/81

Basically, I'll update the plugin to make sure you have a block selected before showing the built in commands like summarize

Let me know if that works. Really appreciate the feedback!

**Comment by mike-lu** [comment]
Thanks for the quick response! I have it working now for summaries of a singular block. What is the intended way to use a set of blocks, such as the whole hierarchy of a master heading, as the input?

**Comment by briansunter** [comment]
I'm working on the multi select block feature now and it will be the next feature I release. Probably at some point this week. https://github.com/briansunter/logseq-plugin-gpt3-openai/issues/41

**Comment by mike-lu** [comment]
Ah ha! Thanks!

**Comment by briansunter** [comment]
You can select multiple blocks now
