### ISSUE TITLE
Custom templates - what am i missing?

### ISSUE THREAD

**Issue by FrankDomburg** [briansunter/logseq-plugin-gpt3-openai#82]
Copy pasted the Student Teacher Dialog prompt from the README.md into a page in my journal
Made sure that the # Student Teacher Dialog line was the very highest level block

Unfortunately, /gpt is not showing a custom template

What am I missing?

**Comment by briansunter** [comment]
Could you post a screenshot off of the template? 

Make sure the code bock is indented beneath the template if it isn't already

**Comment by AvijeetPrasad** [comment]
I was also having the same issue, until I saw your previous comment and realized that we need to indent the prompt. This was not clear from the README. The following syntax works for me.

```
- # Student Teacher Dialog
  prompt-template:: Student Teacher Dialog
	- ```prompt
	  Rewrite text as a dialog between a teacher and a student:
	  ```
```

**Comment by FrankDomburg** [comment]
The identing thing was the problem. Copy-paste from the readme wasn't bringing that in, somehow.

**Comment by FrankDomburg** [comment]
One more thing, if I copy paste as per avijeet above, logseq saysFull content not displayed. For others, your're on the right track, but not quite there yet.

**Comment by briansunter** [comment]
Awesome, glad that fixed it. I'll update the readme with the hyphens so it works with copy and paste.
