### ISSUE TITLE
Doesn't work with chatGPT

### ISSUE THREAD

**Issue by Vitorvlv** [briansunter/logseq-plugin-gpt3-openai#83]
OpenAI just released the chatgpt api:
https://openai.com/blog/introducing-chatgpt-and-whisper-apis

https://platform.openai.com/docs/models/gpt-3-5

I've added "gpt-3.5-turbo"  in openAICompletionEngine in the plugin settings but it doesn't work. 

I get this:
Unknown OpenAI Error

and

![image](https://user-images.githubusercontent.com/26132870/222279586-ec4b45ac-4160-4ff4-b982-e180b962b69c.png)

**Comment by briansunter** [comment]
Hey @Vitorvlv , I'm working on supporting this now. Should be out in a couple days.

This new model requires me to call a new endpoint, unlike the previous models they released, so it takes some changes on my side, but should be pretty straightforward to implement.

Should be a nice update since they say it's as good as the earlier models but 10x cheaper!

**Comment by marcsachet** [comment]
> Hey @Vitorvlv , I'm working on supporting this now. Should be out in a couple days.
> 
> This new model requires me to call a new endpoint, unlike the previous models they released, so it takes some changes on my side, but should be pretty straightforward to implement.
> 
> Should be a nice update since they say it's as good as the earlier models but 10x cheaper!

Great! This is the first thing I tried when I got the email from Open AI this morning: your plug-in is super useful!
In the same vein, as the Whisper API is now available, being able to upload an audio file and get the transcribed text directly in Logeq would be pretty cool!

**Comment by briansunter** [comment]
@marcsachet I'll implement the whisper API integration as well. It would be really cool to take voice notes using the app and then use the plugin to transcribe them

I updated the project roadmap to add that. https://github.com/users/briansunter/projects/1

Right now, I plan on implementing this, then the multi-block select, then the whisper integration.

Should be able to finish the chatgpt pretty quick, then get whisper out in the next couple of weeks.

**Comment by marcsachet** [comment]
> @marcsachet I'll definitely implement the whisper API integration as well. It would be really cool to take voice notes using the app and then use the plugin to transcribe them
> 
> I updated the project roadmap to add that. https://github.com/users/briansunter/projects/1
> 
> Right now, I plan on implementing this, then the multi-block select, then the whisper integration.
> 
> Should be able to finish the chatgpt pretty quick, then get whisper out in the next couple of weeks.

Fantastic! it'll be very cool indeed! and not to mention the possible (almost) on the fly translation!

**Comment by Vitorvlv** [comment]
just gave it a shot, working great, thanks!!

**Comment by briansunter** [comment]
Awesome! Glad you like it!

**Comment by arpagon** [comment]
Thanks, @briansunter This very quick work, is Awesome.

**Comment by Slabhub** [comment]
Still not working for me 
**
![image](https://user-images.githubusercontent.com/75756332/223802597-e7dc26aa-f9b0-4c0b-8256-e7ef1bcb7c6a.png)
**

**Comment by Gawmicro** [comment]
What's the solution for this issue "Unknown OpenAI Error"?

> Still not working for me ** ![image](https://user-images.githubusercontent.com/75756332/223802597-e7dc26aa-f9b0-4c0b-8256-e7ef1bcb7c6a.png) **

First, try to change/regenerate your API key for logseq.
Second, make sure the number "OpenAI Max Tokens" in the plugin setting is 2048 or 1500. It fixed my problem with this.

**Comment by pabloscloud** [comment]
> Still not working for me ** ![image](https://user-images.githubusercontent.com/75756332/223802597-e7dc26aa-f9b0-4c0b-8256-e7ef1bcb7c6a.png) **

same, doesn't work

**Comment by seyoungjeong** [comment]
I see the same error. Has the issue been fixed?
