### ISSUE TITLE
Use selection as input

### ISSUE THREAD

**Issue by wirtzdan** [briansunter/logseq-plugin-gpt3-openai#87]
I often have content spread out over multiple bullet points. Currently, to feed them into my prompts, I have to merge the blocks press CMD + G, and then activate my prompt. 

A better solution would be, that the plugin can detect if there is a selection made. When a selection is made (either in one block, or spanning multiple blocks) all the selected text is taken into the prompt. That could be a super fast approach and could additionally also allow to only take smaller parts of a block and feed it into a prompt. (e.g one sentence that needs to be rewritten)

**Comment by briansunter** [comment]
Hey @wirtzdan, I'm working on this now, and it should be out pretty soon.

https://github.com/briansunter/logseq-plugin-gpt3-openai/issues/41
