### ISSUE TITLE
Prompt Templates

### ISSUE THREAD

**Issue by briansunter** [briansunter/logseq-plugin-gpt3-openai#9]
Create collection of well known working gpt-3 prompts as shorcuts.

https://github.com/semiosis/prompts
https://github.com/semiosis/prompts/tree/master/prompts

```
 I had to write down all the reasons why <1>
  This is my list:
  -
engine: OpenAI Davinci
temperature: 0.8
max-generated-tokens: 200
top-p: 1
cache: true
stop-sequences:
- "\n\n"
```

**Comment by ajk68** [comment]
Awesome! Writing good prompts is so important with GPT3. Looking forward to it!

**Comment by briansunter** [comment]
Added in #70
