### ISSUE TITLE
'Unkown OpenAI Error'

### ISSUE THREAD

**Issue by mcampea** [briansunter/logseq-plugin-gpt3-openai#91]
When trying to summarize a page using '/gpt-page' I often get 'Unkown OpenAI error'.

**Comment by briansunter** [comment]
Hey @mcampea could you add a screenshot of the networking response using the instructions in the Readme. That will help me debug what the issue is.

**Comment by mcampea** [comment]
Seems like it is just hitting max token length.
![image](https://user-images.githubusercontent.com/96329509/225134562-d9bcd304-712d-41c1-87de-4e1ab64bb045.png)

**Comment by mcampea** [comment]
Is there anyway to work around this? i.e., summarize the page in chunks to the API?

**Comment by briansunter** [comment]
I have some upcoming features to support this #21 and #20
For now you'd have to split it into chunks, summarize those, then summarize the summaries.
