### ISSUE TITLE
User Custom Prompt Templates don't work

### ISSUE THREAD

**Issue by yammaku** [briansunter/logseq-plugin-gpt3-openai#93]
Hi, the User custom Prompt Templates don't work. I followed the instruction to create my own prompt template but it does't show up on the GPT popup.
Thanks!

**Comment by encore1733** [comment]
> Hi, the User custom Prompt Templates don't work. I followed the instruction to create my own prompt template but it does't show up on the GPT popup. Thanks!

Same issue. Hope you can look into it. Thanks.

**Comment by briansunter** [comment]
Could you paste an screenshot of what your custom prompts look like? Thanks!

**Comment by encore1733** [comment]
Thanks for the prompt reply! Please review the attached screenshot and let me know if you need any additional info.

![Untitled](https://user-images.githubusercontent.com/750271/225184447-616a416e-ffe4-491d-bed6-67793e9271e6.gif)

**Comment by briansunter** [comment]
Hey @encore1733 I just realized there was a typo in the README example
Could you try updating the codeblock to remove space after the backticks?
So ```prompt instead of ``` prompt

Let me know if that fixes it. I'll update the readme and the code to make it work with the space as well

**Comment by encore1733** [comment]
> Hey @encore1733 I just realized there was a typo in the README example Could you try updating the codeblock to remove space between the triple backticks and the word `prompt`
> 
> So ```prompt 
> instead of
> ``` prompt
> Let me know if that fixes it. I'll update the readme and the code to make it work with the space as well

Thanks. It is fixed by removing the space. Appreciate your work and reply!👍🏻

**Comment by yammaku** [comment]
It works now!

**Comment by briansunter** [comment]
Awesome 👍 Really appreciate you both pointing that out so I can update the README. Hope you find the plugin useful!
