### ISSUE TITLE
Q: Are there plans for GPT-4 integration?

### ISSUE THREAD

**Issue by taro-watanabe** [briansunter/logseq-plugin-gpt3-openai#96]
Not exactly sure if the migration process is straightforward, but are there plans for GPT-4 integration once the API gets public?

**Comment by briansunter** [comment]
It's already been integrated and you should be able to use it today if you have a beta key. I'll try to call out which models are supported more in the README, and maybe even update the name of the repo, now that gpt-4 is out. Let me know what you think!

**Comment by javierfuentesm** [comment]
@briansunter  I couldn't make it work, what thing do I have to change?
