### ISSUE TITLE
I dont see any prompt on the windows version

### ISSUE THREAD

**Issue by BettyNutz** [briansunter/logseq-plugin-gpt3-openai#97]
Obviously there is no cmd button (to press cmd+g) on Windows version of logseq, but I'm on the latest version - with your plugin installed and i dont see the popup as you show in your demo. Im prob just doing something retarded. but it'll be great to get the summery function going. i can type in /gpt that the end of a question and it seems to work ...but no popup like you show

hope you can help

**Comment by briansunter** [comment]
I think it's the windows key on windows. You can customize it in the settings too. I could potentially have it use ctrl on windows if the windows key is inconvenient. Let me know if that works

**Comment by BettyNutz** [comment]
To customize: do i add something in the settings in the json or if its just in general settings under keyboard shortcuts. If so, whats it called ...is the command in others (see [image](https://pasteboard.co/RswfmbwuyjbF.png))?

This is such a stupid question. sorry. Windows 10 has xbox game bar mapped to win+g key.

Appreciate your help

**Comment by briansunter** [comment]
Under the plugin settings you can change it from mod+g to something like ctrl + g

**Comment by BettyNutz** [comment]
its in the latest update! thanks 

solved!
